// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtptf-9_jUz6G8VdoCs16I-iY7c91O_lk',
    appId: '1:213460467250:web:fe7cdcac66b5367188862b',
    messagingSenderId: '213460467250',
    projectId: 'fiap-hackathon-1',
    authDomain: 'fiap-hackathon-1.firebaseapp.com',
    storageBucket: 'fiap-hackathon-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6XHFOADgrWhUJqzd7XirVhTIsU3WqJM',
    appId: '1:213460467250:android:91999f1e2f274a9988862b',
    messagingSenderId: '213460467250',
    projectId: 'fiap-hackathon-1',
    storageBucket: 'fiap-hackathon-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1yK1m4bsIn-V8HV--lB9ZH2CJWf_YbUI',
    appId: '1:213460467250:ios:5705e11ea6d5b93e88862b',
    messagingSenderId: '213460467250',
    projectId: 'fiap-hackathon-1',
    storageBucket: 'fiap-hackathon-1.firebasestorage.app',
    iosBundleId: 'com.example.fiapHackathon',
  );

}